CREATE DATABASE BCN
USE BCN
DROP DATABASE BCN

CREATE TABLE CLIENTE (
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE_COMPLETO VARCHAR (100),
	DIRECCION VARCHAR (200),
	TELEFONO VARCHAR (20)
);

CREATE TABLE TIPO_TARJETA(
	ID INT PRIMARY KEY,
	TIPO_TARJETA VARCHAR (50)
 
 );

 CREATE TABLE FACILITADOR(
	ID_FACILITADOR INT PRIMARY KEY,
	NOMBRE VARCHAR (100)
 );

CREATE TABLE TARJETA(
	ID_TARJETA INT PRIMARY KEY,
	NUMERO_TARJETA VARCHAR(50) UNIQUE,
	FECHA_EXPIRACION DATE,
	ID_TIPO_TARJETA INT FOREIGN KEY REFERENCES TIPO_TARJETA(ID),
	ID_FACILITADOR INT FOREIGN KEY REFERENCES FACILITADOR(ID_FACILITADOR),
	ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE),
);


CREATE TABLE COMPRA (
	ID_COMPRA INT PRIMARY KEY,
	FECHA_COMPRA DATETIME,
	MONTO_GASTADO DECIMAL(10,2),
	DESCRIPCION VARCHAR (200),
	ID_TARJETA INT,
	FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA)
 
 );